# Generated by Django 5.0.4 on 2024-05-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funko_Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('raza', models.CharField(max_length=120)),
                ('edad', models.IntegerField()),
                ('caracteristicas', models.CharField(max_length=120)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Funko_Api.duenio')),
            ],
        ),
    ]
