# Generated by Django 5.0.4 on 2024-05-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funko_Api', '0002_duenio_perros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perros',
            name='duenio',
        ),
        migrations.DeleteModel(
            name='duenio',
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
    ]
