# Generated by Django 5.0.4 on 2024-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bratz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('accesorio', models.BooleanField()),
                ('collection', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
