# Generated by Django 5.0.4 on 2024-06-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('name_autor', models.CharField(max_length=50)),
                ('name_discografica', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('id_song', models.IntegerField()),
            ],
        ),
    ]
