# Generated by Django 5.0.4 on 2024-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simpson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('name_chapter', models.CharField(max_length=100)),
                ('temporada', models.ImageField(upload_to='')),
            ],
        ),
    ]
