# Generated by Django 5.0.4 on 2024-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simpson_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpson',
            name='temporada',
            field=models.IntegerField(),
        ),
    ]
